name = "PlotlyArtifacts"
uuid = "1b8d8d90-ffa2-41b8-b4ef-7f17ea431f2f"
version = "0.0.2"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
LazyArtifacts = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
